import { Command } from "commander";
import fs from "node:fs";
import path from "node:path";
import { createDatabase } from "../../db/schema.js";
import { LearningRepository } from "../../db/repository.js";
import { runAutonomyCycle } from "../../autonomy/index.js";
import { EmbeddingService } from "../../embeddings/index.js";
import { getConfig } from "../../config/index.js";
import { printError, printInfo, printSuccess } from "../output.js";

function ensureDir(target: string): void {
  if (!fs.existsSync(target)) {
    fs.mkdirSync(target, { recursive: true });
  }
}

function installGitHooks(repoRoot: string): void {
  const hooksDir = path.join(repoRoot, ".git", "hooks");
  ensureDir(hooksDir);
  const hookBody = `#!/bin/sh
# generated by code-ltm-cli autonomy init
if command -v code-ltm-cli >/dev/null 2>&1; then
  code-ltm-cli autonomy run --sources git --dry-run >/dev/null 2>&1 || true
fi
`;
  const postCommit = path.join(hooksDir, "post-commit");
  const postMerge = path.join(hooksDir, "post-merge");
  fs.writeFileSync(postCommit, hookBody, { encoding: "utf8", mode: 0o755 });
  fs.writeFileSync(postMerge, hookBody, { encoding: "utf8", mode: 0o755 });
}

function installSchedulerScaffold(repoRoot: string): void {
  const autonomyDir = path.join(repoRoot, ".code-ltm", "autonomy");
  ensureDir(autonomyDir);

  const runScript = path.join(autonomyDir, "run-autonomy.sh");
  const script = `#!/bin/sh
# generated by code-ltm-cli autonomy init
cd "${repoRoot}"
code-ltm-cli autonomy run --maintenance >/tmp/code-ltm-autonomy.log 2>&1
`;
  fs.writeFileSync(runScript, script, { encoding: "utf8", mode: 0o755 });

  const cronLine = `0 */6 * * * ${runScript}`;
  fs.writeFileSync(
    path.join(autonomyDir, "schedule.txt"),
    `Suggested cron entry:\n${cronLine}\n`,
    "utf8"
  );
}

export function registerAutonomyCommand(program: Command): void {
  const autonomy = program
    .command("autonomy")
    .description("Manage autonomous memory ingestion and maintenance");

  autonomy
    .command("init")
    .description("Install git hooks and scheduler scaffold")
    .option("--path <path>", "Project path", process.cwd())
    .action((opts) => {
      try {
        const repoRoot = path.resolve(String(opts.path));
        installGitHooks(repoRoot);
        installSchedulerScaffold(repoRoot);
        printSuccess("Autonomy initialized");
        printInfo(`Git hooks installed in ${path.join(repoRoot, ".git/hooks")}`);
        printInfo(
          `Scheduler scaffold written to ${path.join(repoRoot, ".code-ltm/autonomy/schedule.txt")}`
        );
      } catch (error) {
        printError(
          `Autonomy init failed: ${
            error instanceof Error ? error.message : String(error)
          }`
        );
        process.exit(1);
      }
    });

  autonomy
    .command("run")
    .description("Run a single autonomy collection cycle")
    .option("--path <path>", "Project path", process.cwd())
    .option("--sources <sources>", "Comma-separated: git,tests,pr", "git,tests,pr")
    .option("--maintenance", "Enable maintenance pass", false)
    .option("--dry-run", "Do not write learnings", false)
    .action(async (opts) => {
      try {
        const config = getConfig();
        const db = createDatabase();
        const repo = new LearningRepository(db);
        const embedding = new EmbeddingService(config.embeddings);
        await embedding.initialize();
        repo.setEmbeddingService(embedding);

        const rawSources = String(opts.sources)
          .split(",")
          .map((value) => value.trim())
          .filter(Boolean);
        const validSources = rawSources.filter((source) =>
          ["git", "tests", "pr"].includes(source)
        ) as Array<"git" | "tests" | "pr">;

        const result = await runAutonomyCycle(repo, {
          project_path: path.resolve(String(opts.path)),
          sources: validSources.length > 0 ? validSources : ["git", "tests", "pr"],
          maintenance: !!opts.maintenance,
          dry_run: !!opts.dryRun,
        });

        printSuccess(`Autonomy run ${result.run_id} completed (${result.status})`);
        console.log(JSON.stringify(result, null, 2));
        db.close();
      } catch (error) {
        printError(
          `Autonomy run failed: ${
            error instanceof Error ? error.message : String(error)
          }`
        );
        process.exit(1);
      }
    });

  autonomy
    .command("maintain")
    .description("Run maintenance-only autonomy cycle")
    .option("--path <path>", "Project path", process.cwd())
    .option("--dry-run", "Do not write learnings", false)
    .action(async (opts) => {
      try {
        const config = getConfig();
        const db = createDatabase();
        const repo = new LearningRepository(db);
        const embedding = new EmbeddingService(config.embeddings);
        await embedding.initialize();
        repo.setEmbeddingService(embedding);

        const result = await runAutonomyCycle(repo, {
          project_path: path.resolve(String(opts.path)),
          sources: [],
          maintenance: true,
          dry_run: !!opts.dryRun,
        });

        printSuccess(`Maintenance run ${result.run_id} completed (${result.status})`);
        console.log(JSON.stringify(result, null, 2));
        db.close();
      } catch (error) {
        printError(
          `Autonomy maintenance failed: ${
            error instanceof Error ? error.message : String(error)
          }`
        );
        process.exit(1);
      }
    });
}
